apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
    version: v1
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      version: v1
  template:
    metadata:
      labels:
        app: ui
        version: v1
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/dev-gw/tekton-argocd-sample:8fc5cd0
        imagePullPolicy: Always
        name: ui
        ports:
        - containerPort: 3000
